### ISSUE TITLE
Reused code for gather

### ISSUE THREAD

**Issue by nayr31** [nayr31/N-Toolbox#2]
- Multiple foreach statements should be replaced by a single one that either uses the whitelist on the FVRPhysicalObject set or something relating to combining the arrays into a single one of some type

![image_2021-05-03_212848](https://user-images.githubusercontent.com/69859977/116951700-8dbbeb80-ac56-11eb-874f-289975d007f2.png)

![image_2021-05-03_212927](https://user-images.githubusercontent.com/69859977/116951734-a4fad900-ac56-11eb-8692-e41e06762e8a.png)

**Comment by nayr31** [comment]
Reduced to only using two, since for some reason guns aren't pulled in through the whitelist. 

![image](https://user-images.githubusercontent.com/69859977/117076842-1beeab00-ad05-11eb-9d2e-d2ccecbcf7ec.png)

**Comment by Frityet** [comment]
Solved, close issue

**Comment by nayr31** [comment]
Issue is still present, even though FVRFireArm is in WHITE_TYPES whitelist, it is not pulled through the FindObjectsOfType<> call

![image](https://user-images.githubusercontent.com/69859977/118044862-2f24fa80-b345-11eb-829f-857869b7ea0d.png)

**Comment by nayr31** [comment]
The least of our worries
